### ISSUE TITLE
Compilling fbexport under FreeBSD10

### ISSUE THREAD

**Issue by mariuz** [mariuz/fbexport#1]
Hi, I am attempting to compile fbexport, but unsuccessfully. As FreeBSD use CLANG, I have installed gcc47 from ports, binutils as well, have done some adjustments in make.conf
CC=gcc47
CXX=g++47
CPP=cpp47

And have done some code modification in Makefile. Just replaced g++ with g++47. But error is occurs.

# make exe/fbexport
g++47 -c -O1 -DIBPP_LINUX -DIBPP_GCC -Iibpp -o fbexport/ParseArgs.o fbexport/ParseArgs.cpp
g++47 -c -O1 -DIBPP_LINUX -DIBPP_GCC -Iibpp -o fbexport/FBExport.o fbexport/FBExport.cpp
fbexport/FBExport.cpp: In member function 'std::string FBExport::CreateHumanString(IBPP::Statement&, int)':
fbexport/FBExport.cpp:339:31: error: 'gcvt' was not declared in this scope
fbexport/FBExport.cpp: In member function 'bool FBExport::CreateString(IBPP::Statement&, int, std::string&)':
fbexport/FBExport.cpp:452:31: error: 'gcvt' was not declared in this scope
*** Error code 1

Stop.
make: stopped in /tmp/fbexport-1.90

Would you help me?..

Cheers,
Vitaliy

**Comment by root-ua** [comment]
Hello. I have the same problem on FreeBSD 10.1-RELEASE-p6 amd64.

**Comment by mariuz** [comment]
Please try the version from git

**Comment by rootua** [comment]
It works.
But there are still some warnings:
# g++49 --version
g++49 (FreeBSD Ports Collection) 4.9.3 20150318 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# make
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbcopy/args.o fbcopy/args.cpp
fbcopy/args.cpp:37:0: warning: ignoring #pragma hdrstop  [-Wunknown-pragmas]
 #pragma hdrstop
 ^
fbcopy/args.cpp:164:0: warning: ignoring #pragma package  [-Wunknown-pragmas]
 #pragma package(smart_init)
 ^
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbcopy/fbcopy.o fbcopy/fbcopy.cpp
fbcopy/fbcopy.cpp: In member function 'void FBCopy::disableTriggers()':
fbcopy/fbcopy.cpp:143:53: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if (ar->FireTriggers || ar->Operation != opCopy && ar->Operation != opSingle)
                                                     ^
fbcopy/fbcopy.cpp: In member function 'void FBCopy::enableTriggers()':
fbcopy/fbcopy.cpp:174:53: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if (ar->FireTriggers || ar->Operation != opCopy && ar->Operation != opSingle || triggers.empty())
                                                     ^
fbcopy/fbcopy.cpp: In member function 'void FBCopy::setupFromStdin(FBCopy::CompareOrCopy)':
fbcopy/fbcopy.cpp:370:76: warning: unknown conversion type character 'B' in format [-Wformat=]
             printf("<TABLE WIDTH=99% BORDER=0 CELLSPACING=1 CELLPADDING=2>");
                                                                            ^
fbcopy/fbcopy.cpp: In function 'std::string createHumanString(IBPP::Statement&, int, bool&)':
fbcopy/fbcopy.cpp:483:34: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
             sprintf(str, "%ld", x);
                                  ^
fbcopy/fbcopy.cpp:523:47: warning: format '%lli' expects argument of type 'long long int', but argument 3 has type 'int64_t {aka long int}' [-Wformat=]
             sprintf(str, INT64FORMAT, int64val);
                                               ^
fbcopy/fbcopy.cpp:458:11: warning: unused variable 'c' [-Wunused-variable]
     char *c;                // temporary variables, declared here since declaring
           ^
fbcopy/fbcopy.cpp: In member function 'void FBCopy::copyGeneratorValues(const string&, const string&)':
fbcopy/fbcopy.cpp:598:35: warning: format '%lli' expects argument of type 'long long int', but argument 3 has type 'int64_t {aka long int}' [-Wformat=]
     sprintf(tbuf1, INT64FORMAT, x1);
                                   ^
fbcopy/fbcopy.cpp: In member function 'void FBCopy::compareGeneratorValues(const string&, const string&)':
fbcopy/fbcopy.cpp:630:39: warning: format '%lli' expects argument of type 'long long int', but argument 3 has type 'int64_t {aka long int}' [-Wformat=]
         sprintf(tbuf1, INT64FORMAT, x1);
                                       ^
fbcopy/fbcopy.cpp:631:39: warning: format '%lli' expects argument of type 'long long int', but argument 3 has type 'int64_t {aka long int}' [-Wformat=]
         sprintf(tbuf2, INT64FORMAT, x2);
                                       ^
fbcopy/fbcopy.cpp: In member function 'void FBCopy::compare()':
fbcopy/fbcopy.cpp:895:95: warning: unknown conversion type character '>' in format [-Wformat=]
         printf("<TABLE BGCOLOR=BLACK BORDER=0 CELLSPACING=1 CELLPADDING=4 width=100%>\n<TR>\n");
                                                                                               ^
fbcopy/fbcopy.cpp:915:38: warning: format '%d' expects argument of type 'int', but argument 2 has type 'std::list<std::basic_string<char> >::size_type {aka long unsigned int}' [-Wformat=]
             tables.size(), generators);
                                      ^
fbcopy/fbcopy.cpp: In member function 'bool FBCopy::copyData(IBPP::Statement&, IBPP::Statement&, int, int)':
fbcopy/fbcopy.cpp:1263:10: warning: unused variable 'str' [-Wunused-variable]
     char str[30];   // inside "switch" isn't possible
          ^
fbcopy/fbcopy.cpp: In member function 'bool FBCopy::connect(IBPP::Database&, DatabaseInfo)':
fbcopy/fbcopy.cpp:1398:107: warning: too many arguments for format [-Wformat-extra-args]
                 fprintf(stderr, "Reconnecting with new charset...", d.Hostname.c_str(), d.Username.c_str());
                                                                                                           ^
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbcopy/TableDependency.o fbcopy/TableDependency.cpp
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbcopy/main.o fbcopy/main.cpp
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o ibpp/all_in_one.o ibpp/all_in_one.cpp
g++49 ibpp/all_in_one.o fbcopy/args.o fbcopy/fbcopy.o fbcopy/TableDependency.o fbcopy/main.o -oexe/fbcopy -pthread -lfbclient
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbexport/ParseArgs.o fbexport/ParseArgs.cpp
fbexport/ParseArgs.cpp:35:0: warning: ignoring #pragma hdrstop  [-Wunknown-pragmas]
 #pragma hdrstop
 ^
fbexport/ParseArgs.cpp:183:0: warning: ignoring #pragma package  [-Wunknown-pragmas]
 #pragma package(smart_init)
 ^
fbexport/ParseArgs.cpp: In constructor 'Arguments::Arguments(int, char**)':
fbexport/ParseArgs.cpp:102:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i < (sizeof(doubles)/sizeof(char)); i++)
                         ^
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbexport/FBExport.o fbexport/FBExport.cpp
fbexport/FBExport.cpp:721:0: warning: ignoring #pragma warn  [-Wunknown-pragmas]
                             #pragma warn -sig           // to aviod Warning: conversion may lose significant digits
 ^
fbexport/FBExport.cpp:723:0: warning: ignoring #pragma warn  [-Wunknown-pragmas]
                             #pragma warn +sig       // bring it back
 ^
fbexport/FBExport.cpp:1045:0: warning: ignoring #pragma warn  [-Wunknown-pragmas]
                     #pragma warn -sig
 ^
fbexport/FBExport.cpp:1048:0: warning: ignoring #pragma warn  [-Wunknown-pragmas]
                     #pragma warn +sig
 ^
fbexport/FBExport.cpp:1139:0: warning: ignoring #pragma warn  [-Wunknown-pragmas]
                     #pragma warn -sig
 ^
fbexport/FBExport.cpp:1142:0: warning: ignoring #pragma warn  [-Wunknown-pragmas]
                     #pragma warn +sig
 ^
fbexport/FBExport.cpp: In member function 'std::string FBExport::CreateHumanString(IBPP::Statement&, int)':
fbexport/FBExport.cpp:313:34: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
             sprintf(str, "%ld", x);
                                  ^
fbexport/FBExport.cpp:346:47: warning: format '%lli' expects argument of type 'long long int', but argument 3 has type 'int64_t {aka long int}' [-Wformat=]
             sprintf(str, INT64FORMAT, int64val);
                                               ^
fbexport/FBExport.cpp:284:11: warning: unused variable 'c' [-Wunused-variable]
     char *c;                // temporary variables, declared here since declaring
           ^
fbexport/FBExport.cpp: In member function 'bool FBExport::CreateString(IBPP::Statement&, int, std::string&)':
fbexport/FBExport.cpp:423:34: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
             sprintf(str, "%ld", x);
                                  ^
fbexport/FBExport.cpp:429:44: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
             sprintf(str, "%ld", d.GetDate());
                                            ^
fbexport/FBExport.cpp:434:44: warning: format '%ld' expects argument of type 'long int', but argument 3 has type 'int' [-Wformat=]
             sprintf(str, "%ld", t.GetTime());
                                            ^
fbexport/FBExport.cpp:456:47: warning: format '%lli' expects argument of type 'long long int', but argument 3 has type 'int64_t {aka long int}' [-Wformat=]
             sprintf(str, INT64FORMAT, int64val);
                                               ^
fbexport/FBExport.cpp:398:11: warning: unused variable 'c' [-Wunused-variable]
     char *c;                // temporary variables, declared here since declaring
           ^
fbexport/FBExport.cpp: In function 'std::string getAlign(IBPP::Statement&, int)':
fbexport/FBExport.cpp:803:12: warning: enumeration value 'sdArray' not handled in switch [-Wswitch]
     switch (st->ColumnType(col))
            ^
fbexport/FBExport.cpp:803:12: warning: enumeration value 'sdBlob' not handled in switch [-Wswitch]
fbexport/FBExport.cpp:803:12: warning: enumeration value 'sdDate' not handled in switch [-Wswitch]
fbexport/FBExport.cpp:803:12: warning: enumeration value 'sdTime' not handled in switch [-Wswitch]
fbexport/FBExport.cpp:803:12: warning: enumeration value 'sdTimestamp' not handled in switch [-Wswitch]
fbexport/FBExport.cpp:803:12: warning: enumeration value 'sdString' not handled in switch [-Wswitch]
fbexport/FBExport.cpp: In member function 'int FBExport::Import(IBPP::Statement&, FILE*)':
fbexport/FBExport.cpp:743:9: warning: 'size' may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (size == EOF)    // if break was signaled inside for loop (above)
         ^
g++49 -c -O2 -DIBPP_LINUX -DIBPP_GCC -Iibpp -W -Wall -fPIC -o fbexport/cli-main.o fbexport/cli-main.cpp
g++49 ibpp/all_in_one.o fbexport/ParseArgs.o fbexport/FBExport.o fbexport/cli-main.o -oexe/fbexport -pthread -lfbclient
